### PR TITLE
Query remote data

### PR DESCRIPTION
**Pull request by ngscheurich**
The goal of this PR is to get the app set up to use remote data instead of a local JSON file, as per #7.

Firstly, I made some significant modifications to [Pelican](https://github.com/ngscheurich/pelican). It is no longer simply a caching mechanism, but posesses an understanding of *groups* and *events* as abstract concepts, and of their relationship. It still pulls data from our Google Spreadsheet, but instead of just regurgitating the JSON response, it parses it, casts it to Group and Event structures, and compiles an ad-hoc in-memory, relational database. This database can be accessed via a GraphQL endpoint I've set up at https://pelican.freighter.cloud/graphql. Check out the [GraphiQL instance](https://pelican.freighter.cloud/graphiql) to try some queries. For instance, you can get all groups, ordered by most recent event with something like:

```graphql
{
    groupsByEventDate {
      name
      hex
      icon
      fontIcon
      website
      facebook
      twitter
      meetup
      isActive

      events {
        dateTime
      }
    }
  }
```

With all that in place, I added a GraphQL wrapper to our React app, courtesy of [Apollo](https://www.apollographql.com/) and began fetching the data from Pelican instead of the local file. Group cards should also now be sorted by event date, with the "freshest" listed first.

### CODE REVIEW

**Comment by ngscheurich** [comment]
We’ll probably eventually want to replace what is displayed while the data is being fetched with a nice loading animation or somesuch. Currently it just says:

> Loading…

**Comment by james-alt** [comment]
Looks pretty good so far.  We seem to be missing the "location" field, which doesn't appear to be in the API.  I assume it would be fairly simple to add to our script that reads from the Google Sheet, but I wasn't sure where that was located to look.

**Comment by ngscheurich** [comment]
@adamculpepper After wrestling with a bunch of CORS bullshit, the network error you were getting should now be fixed. Pull the latest changes on this branch, and let me know.

**Comment by ngscheurich** [comment]
Good catch, re: the location field, @james-alt. This change actually needs to occur in [Pelican](https://github.com/ngscheurich/pelican). I've created an [issue](https://github.com/ngscheurich/pelican/issues/2) if you'd like to take a crack at it; otherwise I should be able to get to it sometime tomorrow.

**Pull request merged**
